### ISSUE TITLE
feature: auto switch display on an external monitor

### ISSUE THREAD

**Issue by trydofor** [wimpysworld/gpd-pocket2-ubuntu#11] opened 2019-03-27 12:31 UTC
some time, using GPD P2 (M1 for short) to slideshow need an external monitor(called M2) via TYPE-C(HDMI/VGA), 
so, could you please develop this feature,
```
if M2 pulgs in; then; M1 turns off
if M2 plugs out; then; M1 turns on
```
I'v been try , but not works well

**Comment by flexiondotorg** [comment] 2019-04-08 12:42
I've tested this on my GPD Pocket 2 using a USB-C to HDMI adapter. When I plug the adapter into the USB-C port of the Pocket 2 the HDMI monitor is automatically enabled and when I unplug the adapter the HDMI monitor is disabled. The hardware and Ubuntu MATE are working as designed.

I understand that you want the internal panel to be automatically disabled when an external monitor is plugged in. This is not something we want to change in MATE, leaving both displays enabled is intended and is actually useful for presenting so that one screen can show presenter notes while the other shows the slides.

If you want to manually enable/disable the displays that can be achieved via the Display control centre applet :smiley: I am going to close this since the hardware and MATE Desktop is functioning as intended.

**Closed by flexiondotorg** 2019-04-08 12:42 UTC
